[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DCORE_DEBUG_LEVEL=0

; ESP32 전용 Codec 2 공식 저장소 (모든 코드북이 C로 사전 빌드됨)
lib_deps =
    https://github.com/sh123/esp32_codec2_arduino.git